# Changes here will be overwritten by Copier
_commit: v0.3.0
_src_path: gh:veesion-io/template-python-package.git
package_description: Notify when battery is low
package_name: battery_notifier
python_version: '>=3.12'
use_mypy: true
