name: linter & formatter check & type checker
on:
  workflow_call:
  push:
    branches:
      - "*"

concurrency:
  group: linter-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Linter check
        run: make lint-ci
