name: Unit tests
on:
  workflow_call:
  push:
    branches:
      - "*"

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: tooling
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Run unit tests
        run: make test-ci
